### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by k06a** [parity-js/shell#105]
> I'm running:
>
> - **Parity client version**: Parity/v1.10.3-stable-b9ceda3-20180507/x86_64-macos/rustc1.25.0
> - **Parity UI version**: 0.2.1
> - **Operating system**: MacOS 10.13.4
> - **Installed via**: pkg
> - **Fully synchronized**: no
> - **Network**: ethereum
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

Got error on launch: **A JavaScript error occurred in the main process**
```
Uncaught Exception:
Error: spawn EACCES
    at exports._errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:505:9)
    at module.exports (/Applications/Parity UI.app/Contents/Resources/app.asar/.build/electron.js:18231:22)
    at EventEmitter.module.exports (/Applications/Parity UI.app/Contents/Resources/app.asar/.build/electron.js:18197:9)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (/Applications/Parity UI.app/Contents/Resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
```

Then **An error occured while running parity.**
```
Please attach the following debugging info:
OS: darwin
Arch: x64
Channel: beta
Error: Exit code 1, with signal null.
Please also attach the contents of the following file:
/Users/k06a/Library/Application Support/parity-ui/parity.log

Please quit the app and retry again. If the error message persists, please file an issue at https://github.com/parity-js/shell/issues.
```

And then it works fine. Just 2 horrible messages on launch.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/702124/40018269-727dbf36-57c4-11e8-8699-e559ea4bc025.png">
<img width="643" alt="image" src="https://user-images.githubusercontent.com/702124/40018296-89586d82-57c4-11e8-9679-53d9176600ae.png">

**Comment by amaurymartiny** [comment]
The error messages indeed could be improved in this beta version, I'll work on it.

Could you provide the following information:
- Are you running another instance of parity before launching Parity UI?
- Could you paste the output of `ls -la /Users/k06a/Library/Application\ Support/parity-ui`
- Is the file `/Users/k06a/Library/Application Support/parity-ui/parity.log` empty?

**Comment by k06a** [comment]
@amaurymartiny, Hi! Sure:
1. No, but I'm running web-based Slack App and web-based IM+ App.
2. `$ ls -la /Users/k06a/Library/Application\ Support/parity-ui`

    ```
    total 106768
    drwx------  14 k06a  staff       448 14 май 22:16 .
    drwx------+ 89 k06a  staff      2848 14 май 22:13 ..
    drwx------  28 k06a  staff       896 14 май 23:58 Cache
    -rw-r--r--   1 k06a  staff     28672 14 май 22:13 Cookies
    -rw-r--r--   1 k06a  staff         0 14 май 22:13 Cookies-journal
    drwx------   7 k06a  staff       224 14 май 22:13 GPUCache
    drwx------   6 k06a  staff       192 14 май 22:20 Local Storage
    -rw-------   1 k06a  staff        69 14 май 22:16 Preferences
    -rw-r--r--   1 k06a  staff     53248 14 май 23:58 QuotaManager
    -rw-r--r--   1 k06a  staff         0 14 май 23:58 QuotaManager-journal
    drwx------   4 k06a  staff       128 14 май 22:13 Service Worker
    drwx------   4 k06a  staff       128 14 май 22:16 databases
    -rwxr-xr-x@  1 k06a  staff  53529388 14 май 22:13 parity
    -rw-r--r--   1 k06a  staff       785 14 май 22:16 parity.log
    ```
3. `$ cat /Users/k06a/Library/Application\ Support/parity-ui/parity.log`

    ```
    2018-05-14 22:16:45  Starting Parity/v1.11.1-beta-885f45c-20180514/x86_64-macos/rustc1.25.0
    2018-05-14 22:16:45  Keys path /Users/k06a/Library/Application Support/io.parity.ethereum/keys/Foundation
    2018-05-14 22:16:45  DB path /Users/k06a/Library/Application Support/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
    2018-05-14 22:16:45  Path to dapps /Users/k06a/Library/Application Support/io.parity.ethereum/dapps
    2018-05-14 22:16:45  State DB configuration: fast
    2018-05-14 22:16:45  Operating mode: passive
    Client service database error: Error(Msg("IO error: While lock file: /Users/k06a/Library/Application Support/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/LOCK: Resource temporarily unavailable"), State { next_error: None, backtrace: None })
    ```

**Comment by k06a** [comment]
Today I restarted app without this errors.

**Comment by amaurymartiny** [comment]
It probably was a one-time thing, as shown on the last line of the log file `Resource temporarily unavailable` on the lock.

If the errors persists, please file an issue on the main parity repo with that log.
