### ISSUE TITLE
Error: Cannot find module '..'

### ISSUE THREAD

**Issue by quantumproducer** [parity-js/shell#84]
> I'm running:
>
> - **Parity client version**: 0.0.0
> - **Parity UI version**: 0.0.0
> - **Operating system**: OSX
> - **Installed via**: source
> - **Fully synchronized**: temporarily
> - **Network**: kovan
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

I run

`cd ~/parity/ui/shell-0.1.1/ && npm run electron`

and this happens:

```
 installer.nsh  686 bytes          [emitted]
  [37] ./index.electron.js 7.4 kB {0} [built]
  [41] ./util/parityInstallLocation.js 3.05 kB {0} [built]
  [45] ./util/promiseAny.js 2.07 kB {0} [built]
    + 78 hidden modules

> parity-ui@0.1.1 build:embed /Users/quantum/parity/ui/shell-0.1.1
> cross-env EMBED=1 node webpack/embed

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/quantum/parity/ui/shell-0.1.1/node_modules/.bin/cross-env:4:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
npm ERR! code ELIFECYCLE
```

I expected it to launch the UI. It didn't. I uninstalled node_modules, reinstalled then ran again and this works.

Why did this happen? Will this break in the future?

(I never restarted parity cli once during this process)

**Comment by amaurymartiny** [comment]
Hi @quantumproducer, you said you removed `node_modules` and ran again, and it worked. Does that solve this issue?
